stages:
  - build
  - test
  - release
  - publish
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  image: docker:stable-dind
  script:
    - echo "Logging to GitLab Container Registry with CI credentials..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

semantic-release:
  stage: release
  image: enix/semantic-release:gitlab
  only:
    - master
  except:
    - tags
  script:
    - echo $GITLAB_TOKEN
    - semantic-release --ci

publish-docker-hub:
  stage: publish
  only:
    refs:
      - /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
  image: docker:stable-dind
  before_script:
    - docker version
    - export PUBLISH_IMAGE_TAG=$DOCKER_HUB_REPOSITORY/$CI_PROJECT_NAME:${CI_COMMIT_TAG:1}
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $PUBLISH_IMAGE_TAG
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker push $PUBLISH_IMAGE_TAG