version: '3.4'
services:
  www:
    build:
      context: .
    ports:
    - 8000:8000
    - 35729:35729
    restart: "no"
    volumes:
    - "./index.html:/reveal.js/index.html"
    - "./custom.css:/reveal.js/enix.css"